apiVersion: apps/v1
kind: Deployment # creating 'Deployment' object
metadata:
  name: gateway # deploy name
  labels:
    app: gateway # app name
spec:
  replicas: 2
  selector: # find the pod by the metadata label
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: sidhlee/gateway
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-configmap
            - secretRef:
                name: gateway-secret
