#  Manifest file needs 4 required fields: apiVersion, kind, metadata, and spec

# Which version of the Kubernetes API you're using to create this object.
apiVersion: apps/v1
# What kind of object you want to create
# Workload Resources/Deployments: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
# Data that helps uniquely identify the object
metadata:
  # A deployment named "auth" is created
  name: auth
  labels:
    app: auth
# What state you desire for the object - different based on the object kind
spec:
  # Number of desired pods - not just backups
  replicas: 2
  # defines what pod to manage and how
  selector:
    matchLabels:
      # value must matched the label inside template
      app: auth
  strategy:
    # RollingUpdate Deployments support running multiple versions of an application at the same time. (default)
    # VS killing all pods before deploying new release
    type: RollingUpdate
    rollingUpdate:
      # Up to 3 pods can be created during rollingUpdate
      maxSurge: 3
  # configuration for each individual pods
  template:
    metadata:
      labels:
        app: auth
    spec:
      # Pull the image from docker hub and deploy it to k8s
      containers:
        - name: auth
          image: sidhlee/auth
          ports:
            # port that the app is running from
            - containerPort: 5050
          envFrom:
            - configMapRef:
                # must match metadata.name in ConfigMap manifest
                name: auth-configmap
            - secretRef:
                # metadata.name in Secret manifest
                name: auth-secret
