# In production app, this file would be ignored, stored in a safe place
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_PASSWORD: Auth123
  JWT_SECRET: topsecret
# secret contains unstructured key-value pairs (default)
# other types include specific formats of authorization by docker or kubernetes
type: Opaque
