apiVersion: v1
kind: Service
metadata:
  # name of the service
  name: auth
spec:
  selector:
    app: auth
  # IP address is only accessible from the cluster
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
